version: '3'
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmquser
      - RABBITMQ_DEFAULT_PASS=pabbitpassword
      
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    volumes:
      - postgresdata:/var/lib/postgres 
    ports:
      - "5433:5432"
    environment:
      - "POSTGRES_USER=beer_api_user"
      - "POSTGRES_DB=beer_api_db"
      - "POSTGRES_PASSWORD=password"

  logserver:
    image: datalust/seq:latest
    container_name: logserver
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y 

  beer_api:
    image: beerdot/beerdot_api:latest
    build: ./BeerDotApi
    container_name: beer_api
    ports: 
      - "5001:5001"
    depends_on:
      - rabbitmq
      - logserver
      - postgres_db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

volumes:
  postgresdata:
    external: true    
  rabbitmqdata:
    external: true
